### ISSUE TITLE
how to get multi ''output_dim"?

### ISSUE THREAD

**Issue by Leo-WL** [sftekin/spatio-temporal-weather-forecasting#3]
hi ,can you tell me how to predict multi dimentions, for example, l want to predict the next value of T,U,V

**Comment by sftekin** [comment]
Hi, after your message I made modifications you can pull the repo for the changes. 

Previously, 

Weather model makes predictions with size (B, T, M, N, 1) since I wanted to predict only the temperature.  Do you want to predict other features as well? If yes, we need to make predictions with size (B, T, M, N, D), where D is the number of features. I made this one built-in, which means `out_channels` parameter of last convolutional layer is not taken from `config.py`.

After push,
you need to modify weather_model config in `config.py`, 
First you need to specify which features to predict at weather_model ->  batch_gen -> output_dim, where you specify the indexes of features
Second you need to specify indexes of these features on input tensor at parameter weather_model ->  core -> selected_dim
Third you need to change input dimension of decoder at weather_model ->  core -> decoder_params -> input_dim
Finally, you need to specify output dimension at last layer convolution at parameter weather_model ->  core -> output_conv_params -> out_channel

I tried to describe the parameters with the comments near the parameters,
Please free to ask any problem

**Comment by Leo-WL** [comment]
Thanks for your help,Selim,i pulled your new code and it works well
